### ISSUE TITLE
About openworld experiment

### ISSUE THREAD

**Issue by aBenup** [jgongac/WebsiteFingerprinting#3]
Hi author. Your research results are impressive. So I want to reproduce your results, but I have encountered some problems. It would be great if I could get your help. In the open world experiment,  which one should be confused between the monitored web page trace and the unmonitored web page trace? Besides，I do not konw how information leakage is calculated. I am looking forward to your reply. Thank you so much.

**Comment by websitefingerprinting** [comment]
Hi! I am sorry that I did not see your comment. Hope you have solved your problems. If you need any further help, you can email me directly. Thanks!

**Comment by SongTigerCAUC** [comment]
Hello, could you provide the dataset and model for the AWF  (Automated Website Fingerprinting through Deep Learning) paper? I couldn't find any data for the AWF model online, but it is currently one of the most widely used datasets. I would greatly appreciate it if I could get your help.

**Comment by websitefingerprinting** [comment]
@SongTigerCAUC  Hi! I do not have the AWF model. As for the dataset, I have the complete dataset (1150 classes) and a parsed subset dataset (877 classes). Which one do you prefer? 

As the dataset is very large, can you send me an email, and I will give you my public key and transfer the dataset to your destination via scp.
